# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "75108c3f-fc8e-4389-964d-baabdea30872"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :increment_build do
  increment_build_number
  commit_version_bump
end

lane :beta do
  # build your iOS app
  gym(
    scheme: "Shoveled - Debug"
  )

  FASTLANE_ITC_TEAM_NAME = "Josh Walsh"
  increment_build_number
  crashlytics(
    api_token: "8e5af39567b3632a7b65708e7752946fc2cb646d",
    build_secret: "c3dae658ae81da8aec2cac1b65afe21793a6024d1c7532d08c1c9514b26ec731"
  )
  pilot(skip_waiting_for_build_processing: true)

  slack(
    slack_url: "https://hooks.slack.com/services/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"
  )
end

lane :release do
  gym(
    scheme: "Shoveled"
  )
  increment_build_number
  cocoapods
  scan
  sigh
  deliver
  slack(
    slack_url: "https://hooks.slack.com/services/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"
  )
end
